		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>


		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2><?= TITULO_CLIENTES ?></h2>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										<?= TITULO_CREAR_CLIENTES ?>
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<form action="cliente/cliente/crear" method="post" role="form" enctype="multipart/form-data">
										<div class="botonera">
											<div class="form-grupo">
												<button type="submit" class="boton success"><?= BOTON_ENVIAR ?><i class="fa fa-caret-right"></i></button>
												<a href="cliente" class="boton danger"><?= BOTON_CANCELAR ?><i class="fa fa-ban"></i></a>
											</div>
											<div class="form-grupo">
												<label for="empresa" class="movil-12 pc-3"><?= LABEL_NOMBRE_CLIENTES ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
												<div class="movil-12 pc-9">
													<input type="text" name="empresa" id="empresa" placeholder="<?= LABEL_NOMBRE_CLIENTES ?>" required>
												</div>
											</div>
											<div class="form-grupo">
												<label for="contacto" class="movil-12 pc-3"><?= LABEL_CONTACTO_CLIENTES ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
												<div class="movil-12 pc-9">
													<input type="text" name="contacto" id="contacto" placeholder="<?= LABEL_CONTACTO_CLIENTES ?>" required>
												</div>
											</div>
											<div class="form-grupo">
												<label for="mail" class="movil-12 pc-3"><?= LABEL_MAIL_CLIENTES ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
												<div class="movil-12 pc-9">
													<input type="email" name="mail" id="mail" placeholder="<?= LABEL_MAIL_CLIENTES ?>" required>
												</div>
											</div>
											<div class="form-grupo">
												<label for="tele" class="movil-12 pc-3"><?= LABEL_TELE_CLIENTES ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
												<div class="movil-12 pc-9">
													<input type="tel" name="tele" id="tele" placeholder="<?= LABEL_TELE_CLIENTES ?>" required>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->


	<?= $this->insert('html/includes/include') ?>


	<?= $this->insert('html/includes/footer') ?>
