		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>

		<link rel="stylesheet" href="<?php echo PATH_TEMPLATE ?>/css/tablas.css">

		<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
		<script src="https://cdn.datatables.net/rowreorder/1.1.2/js/dataTables.rowReorder.min.js"></script>
		<script src="<?php echo PATH_TEMPLATE ?>/js/tablas.js"></script>

		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2><?= TITULO_MENU ?></h2>
							<div class="panel-botones">
								<a href="menus/menus/crear" class="boton success"><?= BOTON_NUEVO ?></a>
								<button type="button" id="borrarMen" class="boton danger"><?= BOTON_BORRAR ?></button>
								<button type="button" id="activarMen" class="boton info"><?= BOTON_ACTIVAR ?></button>
								<button type="button" id="desactivarMen" class="boton warning"><?= BOTON_DESACTIVAR ?></button>
								<div class="alertas hide" id="ajax_alerta"></div>
							</div>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										<?= TITULO_LISTADO_MENU ?>
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<!-- Para mas info datatables.net -->
									<script>
										$(document).ready(function () {
											var table = $('#tabla-listado').DataTable({
												"language": {
													"sProcessing": "Procesando...",
													"sLengthMenu": "Mostrar _MENU_ registros",
													"sZeroRecords": "No se encontraron resultados",
													"sEmptyTable": "Ningún dato disponible en esta tabla",
													"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
													"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
													"sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
													"sInfoPostFix": "",
													"sSearch": "Buscar:",
													"sUrl": "",
													"sInfoThousands": ",",
													"sLoadingRecords": "Cargando...",
													"oPaginate": {
														"sFirst": "Primero",
														"sLast": "Último",
														"sNext": "Siguiente",
														"sPrevious": "Anterior"
													},
													"oAria": {
														"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
														"sSortDescending": ": Activar para ordenar la columna de manera descendente"
													}
												},
											});

										});
									</script>
									<div id="result"></div>
									<form method="post" id="formid">
										<table id="tabla-listado" cellspacing="0" width="100%">
											<thead>
												<tr role="row">
													<th><?= TITULO_LISTADO_ACCION ?></th>
													<th><?= TITULO_LISTADO_ID ?></th>
													<th><?= TITULO_LISTADO_TITULO ?></th>
													<th><?= TITULO_LISTADO_VISTA ?></th>
													<th><?= TITULO_LISTADO_LINK ?></th>
													<th><?= TITULO_LISTADO_POSICION ?></th>
													<th><?= TITULO_LISTADO_ESTADO ?></th>
													<th><?= TITULO_LISTADO_OPCIONES ?></th>
												</tr>
											</thead>
											<tbody>
												<?php foreach($menus as $u):?>
												<tr role="row">
													<td><input type="checkbox" name="menu_id[]" value="<?= $u['id'] ?>"></td>
													<td><?= $u['id'] ?></td>
													<td><?= $u['titulo']?></td>
													<td><?= $u['vista']?></td>
													<td><?= $u['link'] ?></td>
													<td><?= $u['posicion'] ?></td>
													<td><center><?php if($u['estado'] == 1):?><i class="fa fa-check-square-o" aria-hidden="true"><?php else: ?><i class="fa fa-square-o" aria-hidden="true"><?php endif ?></i></center></td>
													<td><center><a href="menus/menus/editar/<?= $u['id'] ?>" title="<?= BOTON_EDITAR ?>"><i class="fa fa-pencil texto-azul" aria-hidden="true"></i></a><a href="menus/borrar/<?= $u['id'] ?>" title="<?= BOTON_BORRAR ?>"><i class="fa fa-trash texto-rojo" aria-hidden="true"></i></a></center></td>
												</tr>
												<?php endforeach?>
											</tbody>
										</table>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->


	<?= $this->insert('html/includes/include') ?>


	<?= $this->insert('html/includes/footer') ?>


	<script src="<?php echo PATH_TEMPLATE ?>/js/botoneras.js"></script>
