<!DOCTYPE html>
<html lang="es">

	<head>
		<base href="<?= URL ?>" />

		<meta charset="UTF-8">
		<meta name="application-name" content="<?= APP ?>" />
		<meta name="author" content="<?= APP ?>" />
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
		<meta name='copyright' content='<?= APP ?>'>
		<meta name='language' content='ES'>

		<?php if (isset($item)): ?>
			<meta name="rights" content="<?= APP ?>">
			<meta name="title" content="<?= $item['titulo']?>">
			<meta name="author" content="<?= $item['autor']?>">
			<meta property="og:url" content="url">
			<meta property="og:title" content="<?= $item['titulo']?>">
			<meta property="og:type" content="que es? el controller">
			<meta property="og:image" content="<?= $item['foto']?>">
			<meta name="image" content="<?= $item['foto']?>">
			<meta property="og:description" content="<?= $item['metadescripcion']?>">
			<meta name="description" content="<?= $item['metadescripcion']?>">
			<meta property="og:keywords" content="<?= $item['metapalabraclave']?>">
			<meta name="keywords" content="<?= $item['metapalabraclave']?>">
			<meta name="generator" content="Ocrend Framework | AspectoX">
			<meta name='robots' content='index,follow'>
		<?php else: ?>

		<?php endif ?>

		<link rel="apple-touch-icon" sizes="57x57" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192" href="<?= PATH_TEMPLATE ?>/favicon/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="<?= PATH_TEMPLATE ?>/favicon/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="<?= PATH_TEMPLATE ?>/favicon/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="<?= PATH_TEMPLATE ?>/favicon/favicon-16x16.png">
		<link type="image/x-icon" href="<?= PATH_TEMPLATE ?>/favicon/favicon.ico" rel="shortcut icon" />

		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=0.5, maximum-scale=3">


		<title>
			<?= APP ?>
		</title>

		<link href="https://fonts.googleapis.com/css?family=Merriweather:300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

		<!-- Estilos Css -->
		<link rel="stylesheet" href="<?= PATH_TEMPLATE ?>/css/portenio.css">
		<link rel="stylesheet" href="<?= PATH_TEMPLATE ?>/css/template.css">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>

	</head>

	<body>
