							<div class="panel color-bg-primary">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-file-text-o"></i>
										<?= TITULO_WIDGET_VISITAS ?>
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
										<?php
											echo "<ul>";
											$visita = new Visitas;
											$sr = $visita->showResult();
											$data = $sr->fetchAll();
											echo "Usuarios: <strong>" . $data[0]['countid'] . "</strong><br>";
											echo "Pais: <strong>" . $data[0]['countryName'] . "</strong><br>";
											echo "Navegador: <strong>" . $data[0]['navegador'] . "</strong><br>";
											echo "OS: <strong>" . $data[0]['plataforma'] . "</strong><br>";
										?>
								</div>
							</div>
