<?php
	if(!session_id()){
		session_start();
	}

	use Facebook\Facebook;
	use Facebook\Exceptions\FacebookResponseException;
	use Facebook\Exceptions\FacebookSDKException;

	$fbPermissions 	= array('email');

	$fb = new Facebook(array(
		'app_id' => AUTH_ID,
		'app_secret' => AUTH_SECRET,
		'default_graph_version' => 'v2.2',
	));

	$helper = $fb->getRedirectLoginHelper();

	$mensaje_erro = "";

	// Facebook login
	if(isset($accessToken)){
		if(isset($_SESSION['facebook_access_token'])){
			$fb->setDefaultAccessToken($_SESSION['facebook_access_token']);
		}else{
			// Put short-lived access token in session
			$_SESSION['facebook_access_token'] = (string) $accessToken;

			  // OAuth 2.0 client handler helps to manage access tokens
			$oAuth2Client = $fb->getOAuth2Client();

			// Exchanges a short-lived access token for a long-lived one
			$longLivedAccessToken = $oAuth2Client->getLongLivedAccessToken($_SESSION['facebook_access_token']);
			$_SESSION['facebook_access_token'] = (string) $longLivedAccessToken;

			// Set default access token to be used in script
			$fb->setDefaultAccessToken($_SESSION['facebook_access_token']);
		}

		// Redirect the user back to the same page if url has "code" parameter in query string

		if(isset($_GET['code'])){
			header('Location: ./');
		}

		// Getting user facebook profile info
		try {
			$profileRequest = $fb->get('/me?fields=name,first_name,last_name,email,link,gender,locale,picture');
			$fbUserProfile = $profileRequest->getGraphNode()->asArray();
		} catch(FacebookResponseException $e) {
			$mensaje_erro = 'Graph returned an error: ' . $e->getMessage();
			session_destroy();
			// Redirect user back to app login page
			header("Location: ./");
			exit;
		} catch(FacebookSDKException $e) {
			$mensaje_erro = 'Facebook SDK returned an error: ' . $e->getMessage();
			//exit;
		}

		// Initialize User class
		$user = new Users();

		// Insert or update user data to the database
		$fbUserData = array(
			'oauth_provider'=> 'facebook',
			'oauth_uid' 	=> $fbUserProfile['id'],
			'first_name' 	=> $fbUserProfile['first_name'],
			'last_name' 	=> $fbUserProfile['last_name'],
			'email' 		=> $fbUserProfile['email'],
			'gender' 		=> $fbUserProfile['gender'],
			'locale' 		=> $fbUserProfile['locale'],
			'picture' 		=> $fbUserProfile['picture']['url'],
			'link' 			=> $fbUserProfile['link']
		);
		$userData = $user->checkUser($fbUserData);

		// Put user data into session
		$_SESSION['userData'] = $userData;

		// Get logout url
		$logoutURL = $helper->getLogoutUrl($accessToken, REDIRECT_URL.'logout/');

		// Render facebook profile data
		if(!empty($userData)){
			$fb_user  = '<div class="facebook margin-bottom-normal">';
			$fb_user .= '<h5 class="facebook">Facebook</h5>';
			$fb_user .= '<img src="'.$userData['picture'].'" class="imagen_social">';
			$fb_user .= '<span>Name : ' . $userData['first_name'] . ' ' . $userData['last_name'] . '<span>';
			$fb_user .= '<span>Email : ' . $userData['email'] . '<span>';
			$fb_user .= '<a href="'.$userData['link'].'" target="_blank" class="boton-social-grande facebook margin-top-normal"><i class="fa fa-facebook-square" aria-hidden="true"></i> | Facebook Page</a>';
			$fb_user .= '<a href="'.$logoutURL.'" class="boton primary">Logout</a>';
			$fb_user .= '</div>';
		}else{
			$fb_user = '<div class="alert alert-danger"><span class="fa fa-exclamation-circle" aria-hidden="true"></span>Some problem occurred, please try again.</div>';
		}

	}else{
		// Get login url
		$loginURL = $helper->getLoginUrl(REDIRECT_URL, $fbPermissions);

		// Render facebook login button
		$fb_user = '<a href="'.htmlspecialchars($loginURL).'" class="boton-social-grande facebook"><i class="fa fa-facebook-square" aria-hidden="true"></i> | Login en facebook</a>';
	}

	echo $fb_user;

?>
