		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>


		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2><?= TITULO_POSICIONES ?></h2>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										<?= TITULO_CREAR_POSICIONES ?>
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<form action="posicion/posicion/crear" method="post" role="form" enctype="multipart/form-data">
										<div class="botonera">
											<div class="form-grupo">
												<button type="submit" class="boton success"><?= BOTON_ENVIAR ?><i class="fa fa-caret-right"></i></button>
												<a href="posicion" class="boton danger"><?= BOTON_CANCELAR ?><i class="fa fa-ban"></i></a>
											</div>
											<div class="form-grupo">
												<label for="nombre" class="movil-12 pc-3"><?= LABEL_NOMBRE_POSICIONES ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
												<div class="movil-12 pc-9">
													<input type="text" name="nombre" id="nombre" placeholder="<?= LABEL_NOMBRE_POSICIONES ?>" required>
												</div>
											</div>
											<div class="form-grupo">
												<label for="paginas" class="movil-12 pc-3"><?= LABEL_PAGINAS_POSICIONES ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
												<div class="movil-12 pc-9">
													<input type="text" name="paginas" id="paginas" placeholder="<?= LABEL_PAGINAS_POSICIONES ?>" required>
												</div>
											</div>
											<div class="form-grupo">
												<label for="publica" class="movil-12 pc-3"><?= CAMPO_FORM_ACTIVAR ?></label>
												<div class="movil-12 pc-9">
													<input type="checkbox" name="publica" value="1">
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->


	<?= $this->insert('html/includes/include') ?>


	<?= $this->insert('html/includes/footer') ?>
