<?= $this->insert('overall/header') ?>
  <body>
	<div class="container">
	  <div class="presentacion center">
		<div class="row">
		  <div class="col-xs-12">
			<h1>Ocrend Framework</h1>
			<p>Framework MVC PHP 7. Para expertos y aprendices.</p>
			<p>Estás usando <a href="http://platesphp.com/" target="_blank">PlatesPHP</a> :)</p>

			<h1>Cuenta</h1>

		  </div>
		</div>
	  </div>
	</div>
	<?= $this->insert('overall/footer') ?>
  </body>
</html>
