		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>

		<script src="<?= SITE_URL ?>/extras/tinymce/tinymce.min.js"></script>
		<script type="text/javascript">
			tinymce.init({
				selector: '#texto',
				theme: "modern",
				theme: "modern",
				height: 400,
				plugins: [
					 "advlist autolink link image lists charmap print preview hr anchor pagebreak",
					 "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking spellchecker",
					 "table contextmenu directionality emoticons paste textcolor responsivefilemanager youtube codemirror"
			   ],
				relative_urls: false,
				convert_urls: false,
				browser_spellcheck : true,
				//filemanager_crossdomain: true,
				filemanager_title:"Explorador archivos media",
				external_filemanager_path:"/a-diario/extras/filemanager/",
				external_plugins: { "filemanager" : "plugins/responsivefilemanager/plugin.min.js"},
				codemirror: {
					indentOnInit: true, // Whether or not to indent code on init.
					path: 'CodeMirror'
			   },
			   image_advtab: true,
			   toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
			   toolbar2: "| responsivefilemanager | image | media | link unlink anchor | print preview code | youtube | forecolor backcolor | pagebreak"

			});
		</script>
		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2>Usuarios</h2>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										Crear nuevo usuario
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<form action="users/crear" method="post" role="form" enctype="multipart/form-data">
										<div class="botonera">
											<div class="form-grupo">
												<button type="submit" class="boton success">Enviar<i class="fa fa-caret-right"></i></button>
												<a href="users" class="boton danger">Cancelar<i class="fa fa-ban"></i></a>
											</div>
										</div>
										<div class="form-grupo">
											<label for="nom" class="movil-12 pc-3">Nombre<span class="marcador-rojo"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="text" name="nom" id="nom" placeholder="Nombre" required>
											</div>
										</div>
										<div class="form-grupo">
											<label for="ape" class="movil-12 pc-3">Apellido<span class="marcador-rojo"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="text" name="ape" id="ape" placeholder="Apellido" required>
											</div>
										</div>
										<div class="form-grupo">
											<label for="fnaci" class="movil-12 pc-3">Fecha de nacimiento<span class="marcador-rojo"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="date" name="fnaci" value="2011-08-19" id="example-date-input">
											</div>
										</div>
										<div class="form-grupo">
											<label class="movil-12 pc-3">Sexo<span class="marcador-rojo"> *</span></label>
											<div class="movil-12 pc-9">
												<div class="botonSiNo">
													<label class="on">
														<input type="radio" name="sexo" value="m" checked>
														<span>Masculino</span>
													</label>
													<label class="off">
														<input type="radio" name="sexo" value="f">
														<span>Femenino</span>
													</label>
												</div>
											</div>
										</div>
										<div class="form-grupo">
											<label for="user" class="movil-12 pc-3">Nombre usuario<span class="marcador-rojo"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="text" name="user" id="user" placeholder="Nombre usuario" required>
											</div>
										</div>
										<div class="form-grupo">
											<label for="mail" class="movil-12 pc-3">Email<span class="marcador-rojo"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="email" name="mail" id="mail" placeholder="Email" required>
											</div>
										</div>
										<div class="form-grupo">
											<label for="pass" class="movil-12 pc-3">Clave<span class="marcador-rojo"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="password" name="pass" id="pass" placeholder="Clave" required>
											</div>
										</div>
										<div class="form-grupo">
											<label for="zoneregion" class="movil-12 pc-3">Zona horaria<span class="marcador-rojo"> *</span></label>
											<div class="movil-12 pc-9">
												<select id="zoneregion" name="zoneregion" class="custom-select">
													<option value="0" selected="selected">- Usar la predeterminada -</option>
													<?php
														$regions = array(
															'Africa' => DateTimeZone::AFRICA,
															'America' => DateTimeZone::AMERICA,
															'Antarctica' => DateTimeZone::ANTARCTICA,
															'Aisa' => DateTimeZone::ASIA,
															'Atlantic' => DateTimeZone::ATLANTIC,
															'Europe' => DateTimeZone::EUROPE,
															'Indian' => DateTimeZone::INDIAN,
															'Pacific' => DateTimeZone::PACIFIC
														);
														$timezones = array();
														foreach ($regions as $name => $mask)
														{
															$zones = DateTimeZone::listIdentifiers($mask);
															foreach($zones as $timezone)
															{
																// Lets sample the time there right now
																$time = new DateTime(NULL, new DateTimeZone($timezone));
																// Us dumb Americans can't handle millitary time
																$ampm = $time->format('H') > 12 ? ' ('. $time->format('g:i a'). ')' : '';
																// Remove region name and add a sample time
																$timezones[$name][$timezone] = substr($timezone, strlen($name) + 1);
															}
														}

														foreach($timezones as $region => $list)
														{
															print '<optgroup label="' . $region . '">' . "\n";
															foreach($list as $timezone => $name)
															{
																print '<option name="' . $timezone . '">' . $name . '</option>' . "\n";
															}
															print '<optgroup>' . "\n";
						}
													?>
												</select>
											</div>
										</div>


										<div class="form-grupo">
											<label class="movil-12 pc-3">Avatar usuario</label>
											<div class="fileinput movil-12 pc-9">
												<input  id="imagen" name="imagen" type="text" value="" class="file-input margin-bottom-normal" placeholder="No hay archivo seleccionado...">
												<a href="javascript:open_popup('/a-diario/administracion/extras/filemanager/dialog.php?type=0&popup=1&field_id=imagen&relative_url=avatar/')" class="boton boton-file info" type="button">Seleccionar</a>
											</div>
										</div>

										<?php if ($_SESSION['GRUPO'] == 6) :?>
											<div class="form-grupo">
												<label class="movil-12 pc-3">Jerarquía<span class="marcador-rojo"> *</span></label>
												<div class="movil-12 pc-9">
													<select id="grupo" name="grupo" class="custom-select">
														<option value="1">Publico</option>
														<option value="2">Registrado</option>
														<option value="3">Autor</option>
														<option value="4">Editor</option>
														<option value="5">Administrator</option>
														<option value="6">Super Users</option>
													</select>
												</div>
											</div>

											<div class="form-grupo">
												<label class="movil-12 pc-3">Activar</label>
												<div class="movil-12 pc-9">
													<input type="checkbox" name="activar" value="0">
												</div>
											</div>

											<div class="form-grupo">
												<label class="movil-12 pc-3">Banear</label>
												<div class="movil-12 pc-9">
													<input type="checkbox" name="blquear" value="0">
												</div>
											</div>
										<?php endif ?>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->

	<script>
		function open_popup(url){
			var w = 880;
			var h = 570;
			var l = Math.floor((screen.width-w)/2);
			var t = Math.floor((screen.height-h)/2);
			var win = window.open(url, 'Explorador archivos multimedia', "scrollbars=1,width=" + w + ",height=" + h + ",top=" + t + ",left=" + l);
		}
	</script>

	<?= $this->insert('html/includes/include') ?>


	<?= $this->insert('html/includes/footer') ?>
