		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>

		<script src="<?= SITE_URL ?>/extras/tinymce/tinymce.min.js"></script>
		<script type="text/javascript">
			tinymce.init({
				selector: '#texto',
				theme: "modern",
				theme: "modern",
				height: 400,
				plugins: [
					 "advlist autolink link image lists charmap print preview hr anchor pagebreak",
					 "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking spellchecker",
					 "table contextmenu directionality emoticons paste textcolor responsivefilemanager youtube codemirror"
			   ],
				relative_urls: true,
				convert_urls: true,
				base_url: "a-diario/",
				current_path:"../../administracion/avatar/",
				browser_spellcheck : true,
				//filemanager_crossdomain: true,
				filemanager_title:"Explorador archivos media",
				external_filemanager_path:"/a-diario/extras/filemanager/",
				external_plugins: { "filemanager" : "plugins/responsivefilemanager/plugin.min.js"},
				codemirror: {
					indentOnInit: true, // Whether or not to indent code on init.
					path: 'CodeMirror'
			   },
			   image_advtab: true,
			   toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
			   toolbar2: "| responsivefilemanager | image | media | link unlink anchor | print preview code | youtube | forecolor backcolor | pagebreak"

			});
		</script>
		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2><?= TITULO_USUARIOS ?></h2>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										<?= TITULO_EDITAR_USUARIOS ?>: <?= $users['user']?>
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<form action="users/users/editar/<?= $users['id']?>" method="post" role="form" enctype="multipart/form-data">
										<div class="botonera">
											<div class="form-grupo">
												<button type="submit" class="boton success"><?= BOTON_ENVIAR ?><i class="fa fa-caret-right"></i></button>
												<a href="users/users" class="boton danger"><?= BOTON_CANCELAR ?><i class="fa fa-ban"></i></a>
											</div>
										</div>
										<div class="form-grupo">
											<label for="nom" class="movil-12 pc-3"><?= LABEL_NOMBRE_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="text" name="nom" id="nom" placeholder="<?= LABEL_NOMBRE_USUARIOS ?>" required value="<?= $users['nombre']?>">
											</div>
										</div>
										<div class="form-grupo">
											<label for="ape" class="movil-12 pc-3"><?= LABEL_APELLIDO_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="text" name="ape" id="ape" placeholder="<?= LABEL_APELLIDO_USUARIOS ?>" required value="<?= $users['apellido']?>">
											</div>
										</div>
										<div class="form-grupo">
											<label for="fnaci" class="movil-12 pc-3"><?= LABEL_FECHA_NACIDO_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="date" name="fnaci" value="<?= date('Y-m-d',strtotime($users['nacido'])); ?>" id="example-date-input">
											</div>
										</div>
										<div class="form-grupo">
											<label class="movil-12 pc-3"><?= LABEL_SEXO_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
											<div class="movil-12 pc-9">
												<div class="botonSiNo">
													<label class="on">
														<input type="radio" name="sexo" value="m" <?php if ($users['sexo'] == 'm'){echo "checked";}?>>
														<span><?= LABEL_SEXO_MASCULINO_USUARIOS ?></span>
													</label>
													<label class="off">
														<input type="radio" name="sexo" value="f" <?php if ($users['sexo'] == 'f'){echo "checked";}?>>
														<span><?= LABEL_SEXO_FEMENINO_USUARIOS ?></span>
													</label>
												</div>
											</div>
										</div>
										<div class="form-grupo">
											<label for="user" class="movil-12 pc-3"><?= LABEL_NOMBREUSUARIO_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="text" name="user" id="user" placeholder="<?= LABEL_NOMBREUSUARIO_USUARIOS ?>" required value="<?= $users['user']?>">
											</div>
										</div>
										<div class="form-grupo">
											<label for="mail" class="movil-12 pc-3"><?= LABEL_EMAIL_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="email" name="mail" id="mail" placeholder="<?= LABEL_EMAIL_USUARIOS ?>" required value="<?= $users['email']?>">
											</div>
										</div>
										<div class="form-grupo">
											<label for="pass" class="movil-12 pc-3"><?= LABEL_CLAVE_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
											<div class="movil-12 pc-9">
												<input type="password" name="pass" id="pass" placeholder="<?= LABEL_CLAVE_USUARIOS ?>" disabled>
											</div>
										</div>
										<div class="form-grupo">
											<label for="zoneregion" class="movil-12 pc-3"><?= LABEL_ZONAHORARIA_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
											<div class="movil-12 pc-9">
												<select id="zoneregion" name="zoneregion" class="custom-select">
													<option value="<?php if ($users['zoneregion'] == '0'){ echo '0';}else{echo $users['zoneregion'];}?>" selected="selected"><?php if ($users['zoneregion'] == '0'){ echo TEXTO_SELECCIONAR_OPCION;}else{echo $users['zoneregion'];}?></option>
													<?php
														$regions = array(
															'Africa' => DateTimeZone::AFRICA,
															'America' => DateTimeZone::AMERICA,
															'Antarctica' => DateTimeZone::ANTARCTICA,
															'Aisa' => DateTimeZone::ASIA,
															'Atlantic' => DateTimeZone::ATLANTIC,
															'Europe' => DateTimeZone::EUROPE,
															'Indian' => DateTimeZone::INDIAN,
															'Pacific' => DateTimeZone::PACIFIC
														);
														$timezones = array();
														foreach ($regions as $name => $mask)
														{
															$zones = DateTimeZone::listIdentifiers($mask);
															foreach($zones as $timezone)
															{
																// Lets sample the time there right now
																$time = new DateTime(NULL, new DateTimeZone($timezone));
																// Us dumb Americans can't handle millitary time
																$ampm = $time->format('H') > 12 ? ' ('. $time->format('g:i a'). ')' : '';
																// Remove region name and add a sample time
																$timezones[$name][$timezone] = substr($timezone, strlen($name) + 1);
															}
														}

														foreach($timezones as $region => $list)
														{
															print '<optgroup label="' . $region . '">' . "\n";
															foreach($list as $timezone => $name)
															{
																print '<option name="' . $timezone . '">' . $name . '</option>' . "\n";
															}
															print '<optgroup>' . "\n";
						}
													?>
												</select>
											</div>
										</div>


										<div class="form-grupo">
											<label class="movil-12 pc-3"><?= LABEL_AVATAR_USUARIOS ?></label>
											<div class="fileinput movil-12 pc-9">
												<input  id="imagen" name="imagen" type="text" value="<?= $users['avatar']?>" class="file-input margin-bottom-normal" placeholder="<?= TEXTO_NOHAYARCHIVO_SELECCIONADO ?>">
												<a href="javascript:open_popup('/a-diario/extras/filemanager/dialog.php?type=0&popup=1&field_id=imagen&relative_url=avatar/')" class="boton boton-file info" type="button"><?= BOTON_SELECCIONAR ?></a>
											</div>
										</div>

										<?php if ($_SESSION['GRUPO'] == 6) :?>
											<div class="form-grupo">
												<label class="movil-12 pc-3"><?= LABEL_GRUPO_USUARIOS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"> *</span></label>
												<div class="movil-12 pc-9">
													<select id="grupo" name="grupo" class="custom-select">
														<option value="1" <?php if ($users['grupo'] == '1'){ echo "selected";} ?>><?= LABEL_GRUPO1_USUARIOS ?></option>
														<option value="2" <?php if ($users['grupo'] == '2'){ echo "selected";} ?>><?= LABEL_GRUPO2_USUARIOS ?></option>
														<option value="3" <?php if ($users['grupo'] == '3'){ echo "selected";} ?>><?= LABEL_GRUPO3_USUARIOS ?></option>
														<option value="4" <?php if ($users['grupo'] == '4'){ echo "selected";} ?>><?= LABEL_GRUPO4_USUARIOS ?></option>
														<option value="5" <?php if ($users['grupo'] == '5'){ echo "selected";} ?>><?= LABEL_GRUPO5_USUARIOS ?></option>
														<option value="6" <?php if ($users['grupo'] == '6'){ echo "selected";} ?>><?= LABEL_GRUPO6_USUARIOS ?></option>
													</select>
												</div>
											</div>

											<div class="form-grupo">
												<label class="movil-12 pc-3"><?= LABEL_ACTIVAR_USUARIOS ?></label>
												<div class="movil-12 pc-9">
													<input type="checkbox" name="activar" value="0" <?php if($users['activado'] == 1){echo "checked";}?>>
												</div>
											</div>

											<div class="form-grupo">
												<label class="movil-12 pc-3"><?= LABEL_BANEAR_USUARIOS ?></label>
												<div class="movil-12 pc-9">
													<input type="checkbox" name="blquear" value="0" <?php if($users['bloquear'] == 1){echo "checked";}?>>
												</div>
											</div>
										<?php endif ?>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->

	<script>
		function open_popup(url){
			var w = 880;
			var h = 570;
			var l = Math.floor((screen.width-w)/2);
			var t = Math.floor((screen.height-h)/2);
			var win = window.open(url, 'Explorador archivos multimedia', "scrollbars=1,width=" + w + ",height=" + h + ",top=" + t + ",left=" + l);
		}
	</script>

	<?= $this->insert('html/includes/include') ?>


	<?= $this->insert('html/includes/footer') ?>
