		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>


		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2><?= TITULO_PERFILES_USUARIOS ?></h2>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										 <?= TITULO_PERFIL_USUARIOS ?><?= $users['user']?>
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<div class="botonera">
										<div class="form-grupo">
											<a href="./" class="boton danger"><?= BOTON_CANCELAR ?><i class="fa fa-ban"></i></a>
										</div>
									</div>
									<div class="movil-12 pc-3 " align="center">
										<img alt="<?= $users['user']?>" src="./avatar/<?= $users['avatar']?>" class="rounded-circle img-fluid img-user">
									</div>
									<div class="movil-12 pc-9">
										<table class="table table-user-information">
											<tbody>
												<tr>
													<td><?= LABEL_NOMBRE_USUARIOS ?>:</td>
													<td><?= $users['nombre']?></td>
												</tr>
												<tr>
													<td><?= LABEL_APELLIDO_USUARIOS ?>:</td>
													<td><?= $users['apellido']?></td>
												</tr>
												<tr>
													<td><?= LABEL_FECHA_NACIDO_USUARIOS ?>:</td>
													<td><?= $users['nacido']?></td>
												</tr>
												<tr>
													<td><?= LABEL_SEXO_USUARIOS ?>:</td>
													<td>
														<?php if ($users['sexo'] == 'm'){echo "Masculino";}?>
														<?php if ($users['sexo'] == 'f'){echo "Femenino";}?>
													</td>
												</tr>
												<tr>
													<td><?= LABEL_ZONAHORARIA_USUARIOS ?>:</td>
													<td><?= $users['zoneregion']?></td>
												</tr>
												<tr>
													<td><?= LABEL_EMAIL_USUARIOS ?>:</td>
													<td><a href="mailto:<?= $users['email']?>"><?= $users['email']?></a></td>
												</tr>
												<tr>
													<td><?= LABEL_FECHA_REGISTRO_USUARIOS ?>:</td>
													<td><?= $users['fechareg']?></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->


	<?= $this->insert('html/includes/include') ?>


	<?= $this->insert('html/includes/footer') ?>
