		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>

		<link rel="stylesheet" href="<?php echo PATH_TEMPLATE ?>/css/tablas.css">

		<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
		<script src="https://cdn.datatables.net/rowreorder/1.1.2/js/dataTables.rowReorder.min.js"></script>
		<script src="<?php echo PATH_TEMPLATE ?>/js/tablas.js"></script>
		<script src="<?php echo PATH_TEMPLATE ?>/js/botonera.js"></script>

		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2>Usuarios</h2>
							<div class="panel-botones">
								<a href="users/users/crear" class="boton success">Nuevo</a>
								<button type="button" id="borrarall" class="boton danger">Borrar</button>
								<button type="button" id="activarall" class="boton info">Activar</button>
								<button type="button" id="desactivarall" class="boton warning">Desactivar</button>
								<div class="alertas hide" id="ajax_alerta"></div>
							</div>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										Listado de usuarios
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<!-- Para mas info datatables.net -->
									<script>
										$(document).ready(function () {
											var table = $('#tabla-listado').DataTable({
												"language": {
													"sProcessing": "Procesando...",
													"sLengthMenu": "Mostrar _MENU_ registros",
													"sZeroRecords": "No se encontraron resultados",
													"sEmptyTable": "Ningún dato disponible en esta tabla",
													"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
													"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
													"sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
													"sInfoPostFix": "",
													"sSearch": "Buscar:",
													"sUrl": "",
													"sInfoThousands": ",",
													"sLoadingRecords": "Cargando...",
													"oPaginate": {
														"sFirst": "Primero",
														"sLast": "Último",
														"sNext": "Siguiente",
														"sPrevious": "Anterior"
													},
													"oAria": {
														"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
														"sSortDescending": ": Activar para ordenar la columna de manera descendente"
													}
												},
												columnDefs: [
													{
														targets: 0,
														visible: false
													}
								]
											});

										});
									</script>
									<div id="result"></div>
									<form method="post" id="formid">
										<table id="tabla-listado" cellspacing="0" width="100%">
											<thead>
												<tr role="row">
													<th>oculto</th>
													<th>Acción</th>
													<th>id</th>
													<th>Nonbre y apellido</th>
													<th>Email</th>
													<th>Estado</th>
													<th>Acción</th>
												</tr>
											</thead>
											<tbody>
											<?php foreach(false != $data ? $data : array() as $d): ?>
												<tr role="row">
													<td><?= $d['id'] ?></td>
													<td style="width: 57px;"><i class="ax ax-drag-drop"></i><input type="checkbox" name="user_id[]" value="<?= $d['id'] ?>"></td>
													<td><?= $d['id'] ?></td>
													<td><?= $d['nombre']?> <?= $d['apellido']?></td>
													<td><a href="mailto:<?= $d['email'] ?>"><?= $d['email'] ?></a></td>
													<td><?php if($d['activado'] == 1):?><i class="fa fa-check-square-o texto-verde" aria-hidden="true"></i><?php else: ?><i class="fa fa-square-o" aria-hidden="true"><?php endif ?></i></td>
													<td>
														<a href="users/users/editar/<?= $d['id'] ?>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
														<a href="users/users/eliminar/<?= $d['id'] ?>"><i class="fa fa-trash" aria-hidden="true"></i></a>
													</td>
												</tr>
											<?php endforeach?>
											</tbody>
										</table>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->


	<?= $this->insert('html/includes/include') ?>
	<script src="<?php echo PATH_TEMPLATE ?>/js/botonera.js"></script>

	<?= $this->insert('html/includes/footer') ?>
