<?= $this->insert('html/includes/header') ?>

<?= $this->insert('html/includes/barra') ?>

<?= $this->insert('html/includes/menu') ?>


<div class="contenido-pagina clearfix" id="contenido-pagina">
    <div class="contenido-pagina-wrapper">
        <div class="contenido-pagina-inner">
            <div id="header-pagina" class="clearfix">
                <div class="header-pagina">
                    <h2><?= TITULO_TRAFICO ?></h2>
                </div>
            </div>
            <!-- Comienza contenido general del sitio -->
            <div class="row">
                <!-- Columna 01 -->
                <div class="movil-12 pc-12">
                    <div class="panel color-bg-info">
                        <div class="panel-header">
                            <h4 class="panel-title">
                                <i class="fa fa-newspaper-o"></i>
                                <?= TITULO_TRAFICO_MENU_XDIA ?>
                            </h4>
                            <div class="panel-controls panel-controls-right">
                                <span class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </span>
                                <span class="close-link">
                                    <i class="fa fa-times"></i>
                                </span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="movil-3">
                                <ul class="menu_trafico">
                                    <li><h4><?= TITULO_TRAFICO ?></h4></li>
                                    <li><a href="trafico/"><?= TITULO_INICIO ?></a></li>
                                    <li><a href="trafico/trafico/xhora"><?= TITULO_TRAFICO_MENU_XHORA ?></a></li>
                                    <li><a href="trafico/trafico/xdia" class="active"><?= TITULO_TRAFICO_MENU_XDIA ?></a></li>
                                    <li><a href="trafico/trafico/xsemana"><?= TITULO_TRAFICO_MENU_XSEMANA ?></a></li>
                                    <li><a href="trafico/trafico/xmes"><?= TITULO_TRAFICO_MENU_XMES ?></a></li>
                                    <li><a href="trafico/trafico/xpagina" style="border-bottom:none"><?= TITULO_TRAFICO_MENU_XPAGINA ?></a></li>
                                    <li><h4><?= TITULO_TRAFICO_REFERIDOS ?></h4></li>
                                    <li><a href="trafico/trafico/xurl"><?= TITULO_TRAFICO_MENU_RURL ?></a></li>
                                    <li><a href="trafico/trafico/xdominio"><?= TITULO_TRAFICO_MENU_RDOMINIO ?></a></li>
                                    <li><a href="trafico/trafico/xmotor"><?= TITULO_TRAFICO_MENU_RBUSQUEDA ?></a></li>
                                    <li><a href="trafico/trafico/xpalabra" style="border-bottom:none"><?= TITULO_TRAFICO_MENU_RPALABRA ?></a></li>
                                    <li><h4><?= TITULO_TRAFICO_SISTEMA ?></h4></li>
                                    <li><a href="trafico/trafico/xbrowser"><?= TITULO_TRAFICO_MENU_BROWSER ?></a></li>
                                    <li><a href="trafico/trafico/xos"><?= TITULO_TRAFICO_MENU_OS ?></a></li>
                                    <li><a href="trafico/trafico/xpantalla"><?= TITULO_TRAFICO_MENU_PANTALLA ?></a></li>
                                    <li><a href="trafico/trafico/xhostname" style="border-bottom:none"><?= TITULO_TRAFICO_MENU_HOSTNAME ?></a></li>
                                </ul>
                            </div>
                            <div class="movil-9">
                                <table class="table-basic">
                                    <tbody>
                                        <caption><?= LABEL_TRAFICO_TITULO_XDIA ?></caption>
                                        <tr>
                                    	  <td COLSPAN="4">&nbsp;</td>
                                    	</tr>
                                    	<tr>
                                          <td COLSPAN="4" align="center"><img src="dailyTraffic/" border="0"></td>
                                        </tr>
                                        <tr>
                                    	  <td COLSPAN="4">&nbsp;</td>
                                    	</tr>
                                    	<tr>
                                          <td COLSPAN="4"><h6><?= LABEL_TRAFICO_VISITA_XDIA ?></h6></td>
                                        </tr>
                                        <?php
                                        $temp = $item['day_info'];
                            			$total = 0;
                            			for($i = 0; $item['day_info'] = $temp; $i++){
                            				if($i % 2){
                            					$bgcolor = "#FFFFFF";
                            				}else{
                            					$bgcolor = "#E6E6E6";
                            				}
                            			?>
                                        <tr>
                            				<td width="7%" height="15">&nbsp;</td>
                            				<td bgcolor="<?= $bgcolor?>">&nbsp;<b><?= $item['day_info']["date"]?></b></td>
                            				<td bgcolor="<?= $bgcolor?>" width="20%" align="right"><b><?= $item['day_info']["daycount"]?></b>&nbsp;&nbsp;</td>
                            			</tr>
                                        <?php
                            				$total += $info['day_info']["daycount"];
                            			}
                            			?>
                                        <tr>
                            				<td height="20">&nbsp;</td>
                            				<td bgcolor="#FFFFFF">&nbsp;<b>Total</b></td>
                            				<td bgcolor="#FFFFFF" align="right"><b><?= $total ?></b>&nbsp;&nbsp;</td>
                            			</tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Finaliza contenido general del sitio -->
        </div>
    </div>
</div>

</div>
<!-- FINALIZA EL WRAPPER -->


<?= $this->insert('html/includes/include') ?>


<?= $this->insert('html/includes/footer') ?>
