<?= $this->insert('html/includes/header') ?>

<?= $this->insert('html/includes/barra') ?>

<?= $this->insert('html/includes/menu') ?>


<div class="contenido-pagina clearfix" id="contenido-pagina">
    <div class="contenido-pagina-wrapper">
        <div class="contenido-pagina-inner">
            <div id="header-pagina" class="clearfix">
                <div class="header-pagina">
                    <h2><?= TITULO_TRAFICO ?></h2>
                </div>
            </div>
            <!-- Comienza contenido general del sitio -->
            <div class="row">
                <!-- Columna 01 -->
                <div class="movil-12 pc-12">
                    <div class="panel color-bg-info">
                        <div class="panel-header">
                            <h4 class="panel-title">
                                <i class="fa fa-newspaper-o"></i>
                                <?= TITULO_TRAFICO_MENU_XHORA ?>
                            </h4>
                            <div class="panel-controls panel-controls-right">
                                <span class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </span>
                                <span class="close-link">
                                    <i class="fa fa-times"></i>
                                </span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="movil-3">
                                <ul class="menu_trafico">
                                    <li><h4><?= TITULO_TRAFICO ?></h4></li>
                                    <li><a href="trafico/"><?= TITULO_INICIO ?></a></li>
                                    <li><a href="trafico/trafico/xhora" class="active"><?= TITULO_TRAFICO_MENU_XHORA ?></a></li>
                                    <li><a href="trafico/trafico/xdia"><?= TITULO_TRAFICO_MENU_XDIA ?></a></li>
                                    <li><a href="trafico/trafico/xsemana"><?= TITULO_TRAFICO_MENU_XSEMANA ?></a></li>
                                    <li><a href="trafico/trafico/xmes"><?= TITULO_TRAFICO_MENU_XMES ?></a></li>
                                    <li><a href="trafico/trafico/xpagina" style="border-bottom:none"><?= TITULO_TRAFICO_MENU_XPAGINA ?></a></li>
                                    <li><h4><?= TITULO_TRAFICO_REFERIDOS ?></h4></li>
                                    <li><a href="trafico/trafico/xurl"><?= TITULO_TRAFICO_MENU_RURL ?></a></li>
                                    <li><a href="trafico/trafico/xdominio"><?= TITULO_TRAFICO_MENU_RDOMINIO ?></a></li>
                                    <li><a href="trafico/trafico/xmotor"><?= TITULO_TRAFICO_MENU_RBUSQUEDA ?></a></li>
                                    <li><a href="trafico/trafico/xpalabra" style="border-bottom:none"><?= TITULO_TRAFICO_MENU_RPALABRA ?></a></li>
                                    <li><h4><?= TITULO_TRAFICO_SISTEMA ?></h4></li>
                                    <li><a href="trafico/trafico/xbrowser"><?= TITULO_TRAFICO_MENU_BROWSER ?></a></li>
                                    <li><a href="trafico/trafico/xos"><?= TITULO_TRAFICO_MENU_OS ?></a></li>
                                    <li><a href="trafico/trafico/xpantalla"><?= TITULO_TRAFICO_MENU_PANTALLA ?></a></li>
                                    <li><a href="trafico/trafico/xhostname" style="border-bottom:none"><?= TITULO_TRAFICO_MENU_HOSTNAME ?></a></li>
                                </ul>
                            </div>
                            <div class="movil-9">
                                <table class="table-basic">
                                    <tbody>
                                        <caption><?= LABEL_TRAFICO_VISITA_XHORA ?></caption>
                                        <tr>
                                          <td colspan="4" align="center"><img src="hourTraffic/" border="0"></td>
                                        </tr>
                                        <tr>
                                          <td colspan="4">
                                              <img src="<?= PATH_TEMPLATE ?>/images/graph_color01.gif" border="_blank" align="absmiddle"> &nbsp;&nbsp; <?= TEXTO_TRAFICO_HOY ?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                              <img src="<?= PATH_TEMPLATE ?>/images/graph_color02.gif" border="_blank" align="absmiddle"> &nbsp;&nbsp; <?= TEXTO_TRAFICO_PROMEDIO ?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                              <i class="fa fa-times" aria-hidden="true" style="color:#FF0000"></i>&nbsp;&nbsp;<?= TEXTO_TRAFICO_PROMEDIOXHOY ?>
                                          </td colspan="4">
                                        </tr>
                                        <tr>
                            				<td colspan="4" bgcolor="#d9d9d9">&nbsp;<b><?= TEXTO_TRAFICO_VISITASPORHORA ?></b></td>
                            			</tr>
                            			<?php
                            			$count_color = 0;
                            			for($i=0; $i<sizeof($hour); $i=$i+2){
                            				if($count_color % 2){
                            					$bg_color = "#FFFFFF";
                            				}else{
                            					$bg_color = "#E6E6E6";
                            				}
                            				$count_color++;
                            				echo "<tr bgcolor=\"".$bg_color."\">";
                            				$check_no = $i + 2;
                            				for($j=$i; $j<$check_no; $j++){
                            					if($sum[0]["sum"] > 0){
                            						$hour_percent = $hour[$j]["count"] / $sum[0]["sum"] * 100;
                            					}else{
                            						$hour_percent = 0;
                            					}
                            					echo "<td width=\"25%\">&nbsp;".$hour[$j]["hour"].":00 - ".$hour[$j]["hour"].":59</td>";
                            					echo "<td width=\"25%\">&nbsp;".sprintf ("%.2f", $hour_percent)."%</td>";
                            				}
                            				echo "</tr>";
                            			}
                            			?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Finaliza contenido general del sitio -->
        </div>
    </div>
</div>

</div>
<!-- FINALIZA EL WRAPPER -->


<?= $this->insert('html/includes/include') ?>


<?= $this->insert('html/includes/footer') ?>
