	<!-- COMIENZA EL HEADER -->
	<div id="header" class="barra-nav">
		<a href="" title="Ax-Admin 1.0" class="logo">
			<img src="<?php echo PATH_TEMPLATE ?>/images/iso-ax-admin.png" alt="Ax-Admin 1.0"> Ax-Admin 1.0
		</a>
		<div class="barra-navbar">
			<div class="toggle-sidebar" id="menu">
				<span>
					<i class="fa fa-reorder"></i>
					<span class="sr-only">Collapse sidebar</span>
				</span>
			</div>
			<div class="right">
				<a href="<?= SITE_URL ?>" title="<?= BOTON_VERSITIO ?>" target="_blank">
					<i class="fa fa-external-link" aria-hidden="true" title="<?= BOTON_VERSITIO ?>"></i>
					<?= SITE_APP ?>
				</a>
				<i class="fa fa-bell-o" title="<?= TEX_ALERTAS ?>"></i>
				<i class="fa fa-cog" title="<?= TEX_CONFIGURACION ?>"></i>
				<a href="logout/"><i class="fa fa-power-off" title="<?= TEX_CERRAR ?>"></i></a>
			</div>
		</div>
	</div>
	<!-- FINALIZA EL HEADER -->
