<!DOCTYPE html>
<html lang="es">

	<head>
		<base href="<?= URL ?>" />

		<meta charset="utf-8" />
		<meta name="application-name" content="<?= APP ?>" />
		<meta name="author" content="AspectoX" />
		<meta http-equiv="x-ua-compatible" content="ie=edge">

		<link rel="apple-touch-icon" sizes="57x57" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="<?= PATH_TEMPLATE ?>/favicon/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192" href="<?= PATH_TEMPLATE ?>/favicon/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="<?= PATH_TEMPLATE ?>/favicon/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="<?= PATH_TEMPLATE ?>/favicon/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="<?= PATH_TEMPLATE ?>/favicon/favicon-16x16.png">
		<link type="image/x-icon" href="<?= PATH_TEMPLATE ?>/favicon/favicon.ico" rel="shortcut icon" />

		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=0.5, maximum-scale=3">


		<title>
			<?= APP ?>
		</title>


		<!-- Estilos Css -->
		<link rel="stylesheet" href="<?= PATH_TEMPLATE ?>/css/portenio.css">
		<link rel="stylesheet" href="<?= PATH_TEMPLATE ?>/css/template.css">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->


		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>

		<script type="text/javascript" src="<?= PATH_TEMPLATE ?>/js/alertify.js"></script>
		<link rel="stylesheet" href="<?= PATH_TEMPLATE ?>/css/alertify.core.css" />
		<link rel="stylesheet" href="<?= PATH_TEMPLATE ?>/css/alertify.default.css" />

	</head>

	<body>
