		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2><?= $titulo_seccion ?></h2>
							<span class="txt"><?= TEX_BIENVENIDO . " " . $_SESSION['USUARIO'] ?></span>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
						<?php
						$mod = new Modulos;
						$m = $mod->get_position_modulos();
							//$this->insert('html/ax-noticias/ax-menu')
							foreach($m as $item){
						?>
						<!-- Columna 01 -->
						<div class="movil-12 pc-8">
							<?php
							if($item['modulo'] == "vistas"){
								echo $this->insert($item['ruta']);
							}
							?>
						</div>
						<!-- Fin columna 01 -->

						<!-- Columna 02 -->
						<div class="movil-12 pc-4">
							
						</div>
						<!-- Fin columna 02 -->

						<?php } ?>

					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->
