		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2><?= $titulo_seccion ?></h2>
							<span class="txt"><?= TEX_BIENVENIDO . " " . $_SESSION['USUARIO'] ?></span>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->

						<!-- Columna 01 -->
						<div class="movil-12 pc-8">
							<?php
								//$this->insert('html/ax-noticias/ax-menu')
							?>

							<?=	$this->insert('html/widgets/visitas/visitasCont');?>
						</div>
						<!-- Fin columna 01 -->

						<!-- Columna 02 -->
						<div class="movil-12 pc-4">
							<?= $this->insert('html/widgets/masleidos/masleidos');?>
						</div>
						<!-- Fin columna 02 -->





					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->
