<!DOCTYPE html>
<html lang="es">
	<head>
		<base href="<?= URL ?>" />

		<meta charset="utf-8" />
		<meta name="application-name" content="<?= APP ?>" />
		<meta name="author" content="www.ocrend.com" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link type="image/x-icon" href="<?php echo PATH_TEMPLATE ?>/favicon.ico" rel="shortcut icon" />

		<!-- Estilos Css -->
		<link rel="stylesheet" href="<?php echo PATH_TEMPLATE ?>/css/ax-estilos.css" rel="stylesheet">


		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		 <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		 <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		<style>
		.page-403 {
			text-align: center;
			background: #ff8c66!important;
		}
		.page-403 .header {
			background: #fff;
			padding: 20px 0;
			-webkit-box-shadow: 0 4px 0 rgba(0,0,0,.1);
			box-shadow: 0 4px 0 rgba(0,0,0,.1);
		}
		.header img.logo{
			width: 200px;
		}
		.page-403 .error-code{
			color: #fff;
			font-size: 120px;
			font-weight: 700;
			line-height: 140px;
			margin-top: 60px;
			text-shadow: 0 4px 0 rgba(0,0,0,.1);
		}
		.page-403 .error-text{
			color: #fff;
			color: rgba(0,0,0,.5);
			font-size: 20px;
			font-weight: 600;
			padding: 0 20px;
		}
		.page-403 .error-text .oops{
			font-size: 50px;
		}
		.page-403 .error-text .hr{
			background: #fff;
			background: rgba(0,0,0,.2);
			display: inline-block;
			height: 5px;
			margin: 20px 0;
			width: 40px;
		}
		</style>

		<title><?= APP ?></title>
	</head>
	<body class="page-403">
		<div class="header">
			<a href="./"><img src="<?php echo PATH_TEMPLATE ?>/images/logo.png" alt="" class="logo"></a>
		</div>
		<div class="error-code">403</div>
		<div class="error-text">
			<span class="oops">OOPS!</span><br>
			<span class="hr"></span>
			<br>
			<?= MENSAJE_ERROR_403 ?>
		</div>
	</body>
</html>
