<?= $this->insert('header') ?>
<body class="framework">

  <div class="logo">
	<h3><?= strtoupper(APP) ?></h3>
  </div>

  <div class="content">
	<div class="ocrend-welcome">
	  <span class="ocrend-welcome">¡404 ERROR!</span>
	  <span class="ocrend-welcome-subtitle">Elemento no encontrado.</span>
	</div>
	<div class="form-actions">
	  <p>Página no encontrada.</p>

	  <?= $this->insert('modules') ?>

	</div>

	<?= $this->insert('footer') ?>

  </div>
</body>
</html>
