							<div class="panel color-bg-success">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-file-text-o"></i>
										<?= TEX_ARTICULOS_MAS_VISITADOS ?>
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<ul class="articulos">
										<?php
											//$art = new Articulos;
											//$a = $art->get_articulos_masleidos();
											//foreach($a as $mas){
											//	echo "<li>
											//			<span class='triangulo' style='border-right-color:" . $mas['cat_color'] . ";'>" . $mas['vistas'] . "</span>
											//			<h3>" . $mas['titulo'] . "</h3>
											//		</li>";
											//}
										?>
									</ul>
								</div>
							</div>
